paths:
  image_dir: "dataset_to_label_2/images"
  label_dir: "dataset_to_label_2/labels"
  vis_dir: "dataset_to_label_2/visualizations_final"

models:
  sam2_root: "models/sam2"
  sam2_checkpoint: "models/sam2/checkpoints/sam2.1_hiera_large.pt"
  sam2_model_cfg: "configs/sam2.1/sam2.1_hiera_l.yaml"

runtime:
  device: "cuda"
  min_mask_area: 20
  save_viz: false

classes:
  id_to_name:
    "0": "sam"
    "1": "buoy"
    "2": "hook"
    "3": "land_pad"
    "4": "lolo"
    "5": "catamaran"
    "6": "boat"
    "7": "person"

ui:
  window_name: "annotator"
  result_window: "preview"